name: Build, Lint, Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  Lint:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Type Check
        run: yarn tsc

  Test:
    name: Build, Then Test
    runs-on: ubuntu-latest
    container:
      image: node:lts
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
